version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci

  - package-ecosystem: npm
    directory: /7nolikov
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /7nolikov
    schedule:
      interval: monthly
